apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: dkg931x2p-python 
  janus-idp.io/tekton: dkg931x2p-python
  backstage.io/kubernetes-id: dkg931x2p-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: dkg931x2p-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  