apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: dkg931x2p-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dkg931x2p-python 
  name: dkg931x2p-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: dkg931x2p-python 
